name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, GitHub Actions !

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Set environment variable
        run: echo 'MY_VARIABLE=This is a variable' >> $GITHUB_ENV

      - name: Display variable
        run: echo "Valeur de MY_VARIABLE:${{ env.MY_VARIABLE }}"

      - name: Display secret
        run: echo "Valeur de MY_SECRET:***"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}

      - name: Create hello.txt
        run: echo "Hello world" > hello.txt

      - name: Display hello.txt content
        run: cat hello.txt

      - name: Install dependencies
        run: npm install

      - name: Generate coverage report
        run: |
          npm install --save-dev coveralls jest
       

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Run tests
        run: npm test

      - name: Upload coverage to Coveralls
        run: npm run coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}


  second-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Second job running
        run: echo "Second job running"
